@StudentAPI_ASPNet_HostAddress = http://localhost:5053

GET {{StudentAPI_ASPNet_HostAddress}}/api/student
Accept: application/json

###

POST {{StudentAPI_ASPNet_HostAddress}}/api/student?classroomId=1
Accept: application/json
Content-Type: application/json

{
  "name": "Phuc",
  "isMale": true
}

###

POST {{StudentAPI_ASPNet_HostAddress}}/api/student?classroomId=1
Accept: application/json
Content-Type: application/json

{
  "name": "Stephen",
  "isMale": true
}

###

PUT {{StudentAPI_ASPNet_HostAddress}}/api/student?classroomId=2
Accept: application/json
Content-Type: application/json

{
  "id": 6,
  "name": "Phuc",
  "isMale": true,
  "email": "phuc16102001@gmail.com"
}

###

GET {{StudentAPI_ASPNet_HostAddress}}/api/student/6
Accept: application/json

###

GET {{StudentAPI_ASPNet_HostAddress}}/api/student/7
Accept: application/json

###

DELETE {{StudentAPI_ASPNet_HostAddress}}/api/student/5
Accept: application/json

###

POST {{StudentAPI_ASPNet_HostAddress}}/api/student/6/enroll?courseId=1
Accept: application/json
Content-Type: application/json

{}

###

POST {{StudentAPI_ASPNet_HostAddress}}/api/student/6/enroll?courseId=2
Accept: application/json
Content-Type: application/json

{}

###

GET {{StudentAPI_ASPNet_HostAddress}}/api/student/6/courses
Accept: application/json
Content-Type: application/json

{}

